name: 'submit'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build:chrome-extension
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: ./build/audion.zip
          keys: ${{ secrets.SUBMIT_KEYS }}
