name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js "14.x"
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Run npm test with xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
